version: '3.6'
services:

  wp_thilak:
    image: wordpress:${WP_THILAK_VERSION}
    container_name: wp_thilak
    volumes:
      - ${WP_THILAK_DATA_DIR}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WP_THILAK_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_THILAK_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WP_THILAK_DB_HOST}
      - WORDPRESS_DB_USER=${WP_THILAK_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_THILAK_DB_PASSWORD}
    depends_on:
      - mysql
    restart: always

  wp_sanne:
    image: wordpress:${WP_SANNE_VERSION}
    container_name: wp_sanne
    volumes:
      - ${WP_SANNE_DATA_DIR}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WP_SANNE_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_SANNE_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WP_SANNE_DB_HOST}
      - WORDPRESS_DB_USER=${WP_SANNE_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_SANNE_DB_PASSWORD}
    depends_on:
      - mysql
    restart: always


  mysql:
    image: mariadb:${MARIADB_VERSION}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WP_THILAK_DATA_DIR}:/var/www/html/${WP_THILAK_DATA_DIR}
      - ${WP_SANNE_DATA_DIR}:/var/www/html/${WP_SANNE_DATA_DIR}
      - ${SSL_CERTS_DIR}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR}:/data/letsencrypt
    depends_on:
      - wp_thilak
      - wp_sanne
    restart: always
