version: '3.7'
services:

  mysql:
    image: mariadb:${MARIADB_VERSION}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - wp_thilak_net
      - wp_sanne_net
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${SSL_CERTS_DIR}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR}:/data/letsencrypt
      - ./server-configs-nginx/h5bp:/etc/nginx/h5bp
      - wp_thilak_data:/var/www/html/wp_thilak
      - wp_sanne_data:/var/www/html/wp_sanne
    networks:
      - wp_thilak_net
      - wp_sanne_net
    restart: always

networks:
  wp_thilak_net:
    external: true
  wp_sanne_net:
    external: true

volumes:
  wp_thilak_data:
    external: true
  wp_sanne_data:
    external: true